# Generated by Django 3.2 on 2023-02-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('behaviour', models.TextField()),
                ('date_of_conclusion', models.DateTimeField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
