# Generated by Django 3.2 on 2023-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitejail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='image',
            field=models.ImageField(default='C:/Users/asus/Downloads/default.png', null=True, upload_to='image'),
        ),
    ]
